QuizApp/QuizApp/Controllers/SecurityController.cs
using QuizApp.Models.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace QuizApp.Controllers
{
    public class SecurityController : Controller
    {
        //database adı/çağırma
        quizAppEntities db = new quizAppEntities();

        // GET: Security
        [AllowAnonymous]
        public ActionResult Login()
        {
            
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(q_kullanici kullanici)
        {
            //database içerisinde girilen kullanıcı adını ve şifreyi arama
            var user = db.q_kullanici.FirstOrDefault(x => x.username == kullanici.username && x.password == kullanici.password);

            if(user!= null)
            {
                FormsAuthentication.SetAuthCookie(user.username,false);//false - cookienin kalıcı olmaması için
                return RedirectToAction("Home", "Home");//giriş başarılı home a yönlendir

            }
            else
            {
                ViewBag.Mesaj= "Kullanıcı adı veya şifre geçersiz.";
                return View();
            }
            
        }
        public ActionResult LogOut()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }
    }
}

QuizApp/QuizApp/Views/Security/Login.cshtml
@model QuizApp.Models.EntityFramework.q_kullanici
@{
    Layout = null;
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
   
    <div class="container">
        <div class="row">
            <div class="col-sm-9 col-md-7 col-lg-5 mx-auto" style="margin-top: 80px;">
                <div class="card card-signin my-5">
                    <div class="card-body">

                        <h5 class="card-title text-center">Giriş Ekranı</h5>
                        @using (Html.BeginForm("Login", "Security", FormMethod.Post))
                        {
                            <div class="form-label-group">
                                @Html.TextBoxFor(m => m.username, new { @class = "form-control", placeholder = "Kullanıcı adı" , required = "required" })
                            </div>
                            <br />
                            <div class="form-label-group">
                                @Html.PasswordFor(m => m.password, new { @class = "form-control", placeholder = "Sifre", required = "required" })
                            </div>

                            <br /><br />
                            <button class="btn btn-lg btn-success btn-block text-uppercase" type="submit">Giriş yap</button>

                            <hr class="my-4">
                        }
                        <h4 style="color:firebrick; text-align: center;">
                            @ViewBag.Mesaj
                        </h4>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>