QuizApp/QuizApp/Controllers/ProfilController.cs
using QuizApp.Models.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace QuizApp.Controllers
{
    [Authorize(Roles = "S")]

    public class ProfilController : Controller
    {
        quizAppEntities db = new quizAppEntities();

        //Grafikler sayfasını açma
        public ActionResult GrafikGoster()
        {
            ViewBag.sinavNo = -1;
            var sinavlar = (db.q_genelSonuc.Distinct()).ToList();
            return View(sinavlar);
        
        }

        //Seçilen sınav numarasına göre grafik oluşturma
        public ActionResult GrafikGoster_(int? sinavNo)
        {
            ViewBag.sinavNo = sinavNo;
            var sinavlar = (db.q_genelSonuc.Distinct()).ToList();

            return View("GrafikGoster", sinavlar);

        }

        //Tek bir sınav sonucu grafiği oluşturma - default son sınav
        public ActionResult AnlikGrafik(int? sinavNo)
        {
            List<string> sinavPuan = GetSinavSonuc(sinavNo);

            var chartSonuc = new Chart(500, 400);
            chartSonuc.AddTitle("Sınav Sonuc Grafiği").AddLegend("Kategori")
                .AddSeries("Puan",
                xValue: new[] { "Anlatım Bozukluğu", "Ekler", "Yazım Kuralları", "Ses Bilgisi", "Sözcükte Anlam", "Sözcük Türleri" },
                yValues: sinavPuan)
                .Write();

            var grafik = File(chartSonuc.ToWebImage().GetBytes(), "image/jpeg");
            var sonuc = "<img src='"+ grafik + "'/>";
            return grafik;

        }
        //Tüm sınavların ortalama sonuc grafiği oluşturma
        public ActionResult GenelGrafik()
        {

            List<string> genelPuan = GetGenelSonuc();

            var chartSonuc = new Chart(500, 400);
            chartSonuc.AddTitle("Genel Sonuc Grafiği").AddLegend("Kategori")
                .AddSeries("Puan",
                xValue: new[] { "Anlatım Bozukluğu", "Ekler", "Yazım Kuralları", "Ses Bilgisi", "Sözcükte Anlam", "Sözcük Türleri" },
                yValues: genelPuan)
                .Write();

            return File(chartSonuc.ToWebImage().GetBytes(), "image/jpeg");
        }

        //Veritabanından istenilen sınav numarasına göre sonuc çekme
        private List<string> GetSinavSonuc(int? Sinav_no)
        {
           

            List<string> returnSonuc = new List<string>();

            int? dbSinav;
            if (Sinav_no == -1)
            {
                dbSinav = ((from ss in db.q_sinavSonuc select ss.sinavNo).Distinct()).Max();

            }
            else
            {
                dbSinav = Sinav_no;
            }

            for (int i = 1; i < 7; i++)
            {
                var dbQuiz = (from ss in db.q_sinavSonuc
                              join k in db.q_kategori on ss.kategoriId equals k.kategoriId
                              where ss.sinavNo == dbSinav && ss.kategoriId == i

                              select new
                              {
                                  quizPuan = ss.puan,

                              }).ToList();

                if (dbQuiz != null)
                {
                    var puanToplam = dbQuiz.AsEnumerable().Sum(q => q.quizPuan);
                    string b = puanToplam.ToString();
                    returnSonuc.Add(b);
                }
                else returnSonuc.Add(" ");

            }

            return returnSonuc;


        }

        //Veritabanından tüm sınav sınavların sonucuna göre ortalama sonuc çekme
        private List<string> GetGenelSonuc()
        {

            List<string> returnSonuc = new List<string>();

            var dbSinavSayisi = (from ss in db.q_sinavSonuc select ss.sinavNo).Max();

            for (int i = 1; i < 7; i++)
            {
                int? puanToplam = 0;
                for (int j = 1; j < dbSinavSayisi + 1; j++)
                {
                    var dbQuiz = from ss in db.q_sinavSonuc
                                 join gs in db.q_genelSonuc on ss.sinavNo equals gs.quizCount
                                 where ss.sinavNo == j && ss.kategoriId == i

                                 select new
                                 {
                                     quizPuan = ss.puan,

                                 };

                    foreach (var puan in dbQuiz)
                    {
                        puanToplam += puan.quizPuan;

                    }
                   

                }

                if (puanToplam != 0)
                {
                    puanToplam = puanToplam / dbSinavSayisi;
                    string b = puanToplam.ToString();
                    returnSonuc.Add(b);
                }
                else returnSonuc.Add(" ");


            }

            return returnSonuc;

        }
    }
}

QuizApp/QuizApp/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Quiz App</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel='stylesheet'
          href='https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css'>

    <link href="~/Content/css/style.css" rel="stylesheet" />



    <style>
        #myProgress {
            width: 100%;
            background-color: #ddd;
        }

        #myBar {
            width: 100%;
            height: 30px;
            background-color: #4CAF50;
        }
    </style>
</head>

<body>


    @Html.Partial("_Navbar")

    <div class="container-fluid">
        @RenderBody()

    </div>

    

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    @RenderSection("scripts", false)


    <script>
        $(document).ready(function () {
          //  setInterval(bak,100);

            $("#sinavStart").click(function () {

                $(".navbarButton").unbind("click");
                $(".navbarButton").css("color", "lightGray");


            });

            $('#secenek').change(function () {

                var dogruCevap = $("input[name='Secenek.dogruCvp']:checked").siblings(".btnCvp").val();
                document.getElementById("dogruCvp").innerHTML = dogruCevap;

            });


            $('#sinavlar').on('change', function () {

                var sinavNo_ = $('#sinavlar').val();
               // alert(sinavNo_);
                $.ajax({

                    url: "/Profil/GrafikGoster_",
                    type: 'POST',
                    data: "&sinavNo=" + sinavNo_,
                    success: function (gelenveri) {

                    },
                    error: function (hata) {


                    }
                });

            });

            var sayac_ = $("#sure").text();
            //alert(sayac_);
            var sayac = parseInt(sayac_);
            //alert(sayac);
            //function bak() {
            //    if (sayac > 0) {
            //        sayac = sayac - 1;
            //        $("#sure").text(sayac);
            //    }
            //    else {
            //        $("#sure").text("süre bitti");
            //    }
            //}
            var elem = document.getElementById("myBar");
            function bak() {

                if (sayac > 0) {
                    //alert("fonk");
                    sayac = sayac - 1;
                    $("#sure").text(sayac);
                    elem.style.width = sayac + "%";
                }
                else {
                    $(location).attr('href', 'Home/Home');
                    //$("#sure").text("Süre Bitti");
                    @*@Url.Action("GenelGrafik","Profil");*@
                }
            }

           // var i = s;


            //function move() {
            //   // if (i == 50) {
            //        //i = 50;
            //       /// var width = i;
            //        var id = setInterval(frame, 1000);
            //        function frame() {
            //            if (i == 0) {
            //                clearInterval(id);
            //               // i = 50;
            //            } else {
            //                i--;

            //                elem.style.width = i + "%";
            //            }
            //        }
            //    //}
            //}
        });
    </script>

    

</body>


</html>

QuizApp/QuizApp/Views/Shared/_Mesaj.cshtml
@model QuizApp.ViewModel.mesajViewModel

<div class="row">
    <div class="col-sm-10  mx-auto ">
        <div class="card card-signin my-5">
            <div class="card-body" style="margin-top:70px;">
               

                @if (Model.Status==1)
                {
                    <div class="alert alert-success">
                        @Model.Mesaj <a href="@Model.Url">@Model.LinkText</a>
                    </div>
                }
                else
                {
                    <div class="alert alert-danger">
                        @Model.Mesaj <a href="@Model.Url">@Model.LinkText</a>
                    </div>

                }


            </div>
        </div>
    </div>
</div>

QuizApp/QuizApp/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <a class="navbar-brand navbarButton" href="~/Home/Home">Anasayfa</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            @*<li class="nav-item active">
            <a class="nav-link" href="~/Quiz/QuizStart">Quiz</a>
        </li>*@
            @if (User.IsInRole("T"))
            {
                <li class="nav-item">
                    <a class="nav-link" href="~/QuizHazirla/QuizOlustur">Soru Hazırla</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="~/QuizHazirla/QuizListele">Sorular Listesi</a>
                </li>
            }
            @if (User.IsInRole("S"))
            {
                <li class="nav-item">
                    <a class="nav-link navbarButton" href="~/Profil/GrafikGoster">Profil</a>
                </li>

            }
            <li class="nav-item">
                <a class="nav-link navbarButton" href="~/Security/LogOut">Çıkış Yap</a>
            </li>
           
            <li>
               
            </li>
        </ul>
    </div>
</nav>