QuizApp/QuizApp/Controllers/QuizHazirlaController.cs
using QuizApp.Models.EntityFramework;
using QuizApp.ViewModel;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace QuizApp.Controllers
{
    [Authorize(Roles = "T")]
    public class QuizHazirlaController : Controller
    {
        quizAppEntities db = new quizAppEntities();

        //Quiz hazırlama ekranı
        public ActionResult QuizOlustur()
        {
            var model = new viewModel()
            {
                Kategori = db.q_kategori.ToList(),
                Soru = new q_soru(),
                Secenek = new q_secenek()

            };

       
            return View("QuizOlustur", model);

        }

        //Soru kaydetme
        [ValidateAntiForgeryToken]
        public ActionResult SoruKaydet(q_soru soru,q_secenek secenek)
        {
            mesajViewModel mesajModel = new mesajViewModel();

            if (!ModelState.IsValid)
            {
                var model_ = new viewModel()
                {
                    Kategori = db.q_kategori.ToList(),
                    Soru = new q_soru(),
                    Secenek = new q_secenek()

                };

                return View("QuizOlustur", model_);
            }
            else
            {
                soru.soruUniq = Guid.NewGuid();
                secenek.soruUniq = soru.soruUniq;
                soru.derece = 0;
                db.q_soru.Add(soru);
                db.q_secenek.Add(secenek);


            }
            db.SaveChanges();

            mesajModel.Mesaj = "Soru Başarıyla Eklendi...";
            mesajModel.Status = 1;
            mesajModel.LinkText = "Yeni Soru Ekle";
            mesajModel.Url = "/QuizHazirla/QuizOlustur";


            return View("_mesaj", mesajModel);
           

        }
        //Tüm soruları listeleme
        public ActionResult QuizListele()
        {
               
            var model = db.q_secenek.Include("q_soru").ToList();

            return View(model);
        }





    }
}

QuizApp/QuizApp/Views/QuizHazirla/QuizListele.cshtml
@model List<QuizApp.Models.EntityFramework.q_secenek>
@{
    ViewBag.Title = "QuizListele";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<div class="container"  style="margin-top:70px;">

    <table class="table table-bordered table-hover">
        <tr style="background-color:lightgreen">
            <th>
                Kategori
            </th>
            <th>
                Soru Metni
            </th>
            <th>
                Secenek
            </th>
            <th>
                Secenek
            </th>
            <th>
                Secenek
            </th>
            <th>
                Secenek
            </th>

            <th></th>
        </tr>

        @foreach (var quiz in Model)
        {
            <tr>
                <td>
                    @(quiz.q_soru.q_kategori.kategori)
                </td>
                <td>
                    @(quiz.q_soru.soru)
                </td>
                <td>
                    @(quiz.cevap1)
                </td>
                <td>
                    @(quiz.cevap2)
                </td>
                <td>
                    @(quiz.cevap3)
                </td>
                <td>
                    @(quiz.cevap4)
                </td>

            </tr>
        }

    </table>


</div>

QuizApp/QuizApp/Views/QuizHazirla/QuizOlustur.cshtml
@model QuizApp.ViewModel.viewModel

@{
    ViewBag.Title = "QuizOlustur";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row">
    <div class="col-sm-9 col-md-7 col-lg-5 mx-auto " id="soruHazirla">
        <div class="card card-signin my-5">
            <div class="card-body">
                <h5 class="text-center"><b>SORU HAZIRLA</b></h5>
                <br /><br />

                @using (Html.BeginForm("SoruKaydet", "QuizHazirla", FormMethod.Post, new { @id = "soruKaydet" }))

                {
                    @Html.AntiForgeryToken()
                    <div class="form-label-group">
                        <div class="row">
                            <div class="col-md-6">
                                <label><b>Kategori Seçiniz:</b></label>
                            </div>
                            <div class="col-md-6">
                                @Html.DropDownListFor(m => m.Soru.kategoriId, new SelectList(Model.Kategori, "kategoriId", "kategori"), "Kategori", new { @class = "form-control", required = "required" })

                            </div>
                        </div>
                    </div>

                    <div class="form-label-group">
                        <label><b>Sorunuzu Yazınız:</b></label>
                        @Html.TextAreaFor(m => m.Soru.soru, new { @class = "form-control soru", required = "required" })


                    </div>
                    <br />

                    <div id="secenek">
                        <label><b>Seçenekleri Yazınız,Doğru Cevabı İşaretleyiniz:</b></label>
                        <div class="form-label-group">
                            <div class="row ">
                                @Html.RadioButtonFor(m => m.Secenek.dogruCvp, "cevap1", new { @class = "form-control col-md-1", @checked = "checked" })
                                @Html.TextBoxFor(m => m.Secenek.cevap1, new { @class = "form-control col-md-11 btnCvp", required = "required" })
                            </div>
                        </div>

                        <br />


                        <div class="form-label-group">

                            <div class="row">
                                @Html.RadioButtonFor(m => m.Secenek.dogruCvp, "cevap2", new { @class = "form-control col-md-1  " })
                                @Html.TextBoxFor(m => m.Secenek.cevap2, new { @class = "form-control col-md-11 btnCvp", required = "required" })
                            </div>
                        </div>

                        <br />
                        <div class="form-label-group">
                            <div class="row">
                                @Html.RadioButtonFor(m => m.Secenek.dogruCvp, "cevap3", new { @class = "form-control col-md-1" })
                                @Html.TextBoxFor(m => m.Secenek.cevap3, new { @class = "form-control col-md-11 btnCvp", required = "required" })
                            </div>
                        </div>

                        <br />

                        <div class="form-label-group">
                            <div class="row">
                                @Html.RadioButtonFor(m => m.Secenek.dogruCvp, "cevap4", new { @class = "form-control col-md-1 " })
                                @Html.TextBoxFor(m => m.Secenek.cevap4, new { @class = "form-control col-md-11 btnCvp", required = "required" })
                            </div>
                        </div>
                        <br />

                        <div class="form-label-group">
                            <div class="row">
                                <h4 id="dogruCvp"></h4>
                            </div>
                        </div>

                    </div>


                    <br /><br />
                    <button class="btn btn-lg btn-success btn-block text-uppercase"  type="submit">Kaydet</button>
                    <hr class="my-4">
                }

            </div>
        </div>
    </div>
</div>
@section scripts
{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}